name: BrAPI
author: Bryan_lzh
authors: ['Bryan_lzh','DarkBlade12']
main: com.github.bryanser.brapi
description: '开发者QQ:390807154'
softdepend: [Vault,ProtocolLib]
version: ${project.version}

commands:
    BrAPI:
        aliases: [bra]
        description: 主命令
        usage: /<command>