name: BrAPI
author: Bryan_lzh
authors: ['Bryan_lzh','龚明秋','DarkBlade12']
main: Br.API.Main
description: '开发者QQ:390807154'
softdepend: [Vault,ProtocolLib]
version: Release-3.4.6

commands:
    BrAPI:
        aliases: [bra]
        description: 主命令
        usage: /<command>