name: BrAPI
authors: ['Bryan_lzh']
main: Br.API.Main
description: '开发者QQ:390807154'
softdepend: [Vault]
version: Release-2.4.2

commands:
  BrAPI:
    aliases: [bra]
    description: 主命令
    usage: /<command>