name: BrAPI
authors: ['Bryan_lzh']
main: Br.API.Main
description: '开发者QQ:390807154  部分代码来源yeongpin99'
softdepend: [Vault]
version: Release-2.6.1

commands:
    BrAPI:
        aliases: [bra]
        description: 主命令
        usage: /<command>