name: BrAPI
authors: ['Bryan_lzh']
#部分代码来源: '龚明秋','yeongpin99'
main: Br.API.Main
description: '开发者QQ:390807154'
softdepend: [Vault,ProtocolLib]
version: Release-3.0.0

commands:
    BrAPI:
        aliases: [bra]
        description: 主命令
        usage: /<command>