name: BrAPI
authors: ['Bryan_lzh','龚明秋','yeongpin99']
main: Br.API.Main
description: '开发者QQ:390807154'
softdepend: [Vault]
version: Release-2.9.0

commands:
    BrAPI:
        aliases: [bra]
        description: 主命令
        usage: /<command>